- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy WAR file to Tomcat
      copy: 
         src: "target/test2.war"
         dest: "/opt/tomcat/webapps/test2.war"
         remote_src: no
         
    -name: Restart Tomcat
    systemd:
       name: tomcat
       state: restarted
